name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: "reason"
        required: false

jobs:
  build_docker_image:
    name: Build and Save Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: new_billing

      - name: Save version info
        run: |
          echo "main-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)" > VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: new-api:latest
          outputs: type=docker,dest=/tmp/new-api.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-api-docker-image
          path: /tmp/new-api.tar
          retention-days: 5

      - name: Commit and push image to repository
        run: |
          mkdir -p docker-images
          cp /tmp/new-api.tar docker-images/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docker-images/new-api.tar
          git commit -m "Add built Docker image [skip ci]"
          git push origin new_billing
